(cl:defpackage panda_move-msg
  (:use )
  (:export
   "<ACTION>"
   "ACTION"
   "<EXECUTIONCHECK>"
   "EXECUTIONCHECK"
   "<PANDAMOVEITJOINTS>"
   "PANDAMOVEITJOINTS"
   "<PANDATRAJECTORY>"
   "PANDATRAJECTORY"
   "<PREDICATE>"
   "PREDICATE"
   "<TRAJECTORYPOINT>"
   "TRAJECTORYPOINT"
   "<ORIENTATION>"
   "ORIENTATION"
   "<POSITION>"
   "POSITION"
  ))

