//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaMove
{
    public class MExecutionCheck : Message
    {
        public const string RosMessageName = "panda_move/ExecutionCheck";

        public long status;

        public MExecutionCheck()
        {
            this.status = 0;
        }

        public MExecutionCheck(long status)
        {
            this.status = status;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.status));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.status = BitConverter.ToInt64(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MExecutionCheck: " +
            "\nstatus: " + status.ToString();
        }
    }
}
