//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaMove
{
    public class MPandaMoveitJoints : Message
    {
        public const string RosMessageName = "panda_move/PandaMoveitJoints";

        public double world_joint;
        public double rail_joint;
        public double base_joint;
        public double panda_joint1;
        public double panda_joint2;
        public double panda_joint3;
        public double panda_joint4;
        public double panda_joint5;
        public double panda_joint6;
        public double panda_joint7;
        public double panda_joint8;
        public double panda_joint_ee;
        public double panda_joint_knife;
        public double panda_joint_spatula;
        public double panda_joint_scooper;
        public double panda_joint_spreader;
        public double panda_hand_joint;
        public double panda_finger_joint1;
        public double panda_finger_joint2;

        public MPandaMoveitJoints()
        {
            this.world_joint = 0.0;
            this.rail_joint = 0.0;
            this.base_joint = 0.0;
            this.panda_joint1 = 0.0;
            this.panda_joint2 = 0.0;
            this.panda_joint3 = 0.0;
            this.panda_joint4 = 0.0;
            this.panda_joint5 = 0.0;
            this.panda_joint6 = 0.0;
            this.panda_joint7 = 0.0;
            this.panda_joint8 = 0.0;
            this.panda_joint_ee = 0.0;
            this.panda_joint_knife = 0.0;
            this.panda_joint_spatula = 0.0;
            this.panda_joint_scooper = 0.0;
            this.panda_joint_spreader = 0.0;
            this.panda_hand_joint = 0.0;
            this.panda_finger_joint1 = 0.0;
            this.panda_finger_joint2 = 0.0;
        }

        public MPandaMoveitJoints(double world_joint, double rail_joint, double base_joint, double panda_joint1, double panda_joint2, double panda_joint3, double panda_joint4, double panda_joint5, double panda_joint6, double panda_joint7, double panda_joint8, double panda_joint_ee, double panda_joint_knife, double panda_joint_spatula, double panda_joint_scooper, double panda_joint_spreader, double panda_hand_joint, double panda_finger_joint1, double panda_finger_joint2)
        {
            this.world_joint = world_joint;
            this.rail_joint = rail_joint;
            this.base_joint = base_joint;
            this.panda_joint1 = panda_joint1;
            this.panda_joint2 = panda_joint2;
            this.panda_joint3 = panda_joint3;
            this.panda_joint4 = panda_joint4;
            this.panda_joint5 = panda_joint5;
            this.panda_joint6 = panda_joint6;
            this.panda_joint7 = panda_joint7;
            this.panda_joint8 = panda_joint8;
            this.panda_joint_ee = panda_joint_ee;
            this.panda_joint_knife = panda_joint_knife;
            this.panda_joint_spatula = panda_joint_spatula;
            this.panda_joint_scooper = panda_joint_scooper;
            this.panda_joint_spreader = panda_joint_spreader;
            this.panda_hand_joint = panda_hand_joint;
            this.panda_finger_joint1 = panda_finger_joint1;
            this.panda_finger_joint2 = panda_finger_joint2;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.world_joint));
            listOfSerializations.Add(BitConverter.GetBytes(this.rail_joint));
            listOfSerializations.Add(BitConverter.GetBytes(this.base_joint));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint1));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint2));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint3));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint4));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint5));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint6));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint7));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint8));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint_ee));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint_knife));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint_spatula));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint_scooper));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_joint_spreader));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_hand_joint));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_finger_joint1));
            listOfSerializations.Add(BitConverter.GetBytes(this.panda_finger_joint2));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.world_joint = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.rail_joint = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.base_joint = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint1 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint2 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint3 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint4 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint5 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint6 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint7 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint8 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint_ee = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint_knife = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint_spatula = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint_scooper = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_joint_spreader = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_hand_joint = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_finger_joint1 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.panda_finger_joint2 = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MPandaMoveitJoints: " +
            "\nworld_joint: " + world_joint.ToString() +
            "\nrail_joint: " + rail_joint.ToString() +
            "\nbase_joint: " + base_joint.ToString() +
            "\npanda_joint1: " + panda_joint1.ToString() +
            "\npanda_joint2: " + panda_joint2.ToString() +
            "\npanda_joint3: " + panda_joint3.ToString() +
            "\npanda_joint4: " + panda_joint4.ToString() +
            "\npanda_joint5: " + panda_joint5.ToString() +
            "\npanda_joint6: " + panda_joint6.ToString() +
            "\npanda_joint7: " + panda_joint7.ToString() +
            "\npanda_joint8: " + panda_joint8.ToString() +
            "\npanda_joint_ee: " + panda_joint_ee.ToString() +
            "\npanda_joint_knife: " + panda_joint_knife.ToString() +
            "\npanda_joint_spatula: " + panda_joint_spatula.ToString() +
            "\npanda_joint_scooper: " + panda_joint_scooper.ToString() +
            "\npanda_joint_spreader: " + panda_joint_spreader.ToString() +
            "\npanda_hand_joint: " + panda_hand_joint.ToString() +
            "\npanda_finger_joint1: " + panda_finger_joint1.ToString() +
            "\npanda_finger_joint2: " + panda_finger_joint2.ToString();
        }
    }
}
