//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaMove
{
    public class MPredicate : Message
    {
        public const string RosMessageName = "panda_move/Predicate";

        public string name;
        public string[] @params;

        public MPredicate()
        {
            this.name = "";
            this.@params = new string[0];
        }

        public MPredicate(string name, string[] @params)
        {
            this.name = name;
            this.@params = @params;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            
            listOfSerializations.Add(BitConverter.GetBytes(@params.Length));
            foreach(var entry in @params)
                listOfSerializations.Add(SerializeString(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            
            var @paramsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.@params= new string[@paramsArrayLength];
            for(var i = 0; i < @paramsArrayLength; i++)
            {
                var @paramsStringBytesLength = DeserializeLength(data, offset);
                offset += 4;
                this.@params[i] = DeserializeString(data, offset, @paramsStringBytesLength);
                offset += @paramsStringBytesLength;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MPredicate: " +
            "\nname: " + name.ToString() +
            "\n@params: " + System.String.Join(", ", @params.ToList());
        }
    }
}
