// Generated by gencpp from file panda_move/ActionSequences.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_ACTIONSEQUENCES_H
#define PANDA_MOVE_MESSAGE_ACTIONSEQUENCES_H

#include <ros/service_traits.h>


#include <panda_move/ActionSequencesRequest.h>
#include <panda_move/ActionSequencesResponse.h>


namespace panda_move
{

struct ActionSequences
{

typedef ActionSequencesRequest Request;
typedef ActionSequencesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionSequences
} // namespace panda_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_move::ActionSequences > {
  static const char* value()
  {
    return "078ea5c2edc52b36bc1237b7034dab03";
  }

  static const char* value(const ::panda_move::ActionSequences&) { return value(); }
};

template<>
struct DataType< ::panda_move::ActionSequences > {
  static const char* value()
  {
    return "panda_move/ActionSequences";
  }

  static const char* value(const ::panda_move::ActionSequences&) { return value(); }
};


// service_traits::MD5Sum< ::panda_move::ActionSequencesRequest> should match
// service_traits::MD5Sum< ::panda_move::ActionSequences >
template<>
struct MD5Sum< ::panda_move::ActionSequencesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::ActionSequences >::value();
  }
  static const char* value(const ::panda_move::ActionSequencesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::ActionSequencesRequest> should match
// service_traits::DataType< ::panda_move::ActionSequences >
template<>
struct DataType< ::panda_move::ActionSequencesRequest>
{
  static const char* value()
  {
    return DataType< ::panda_move::ActionSequences >::value();
  }
  static const char* value(const ::panda_move::ActionSequencesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_move::ActionSequencesResponse> should match
// service_traits::MD5Sum< ::panda_move::ActionSequences >
template<>
struct MD5Sum< ::panda_move::ActionSequencesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::ActionSequences >::value();
  }
  static const char* value(const ::panda_move::ActionSequencesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::ActionSequencesResponse> should match
// service_traits::DataType< ::panda_move::ActionSequences >
template<>
struct DataType< ::panda_move::ActionSequencesResponse>
{
  static const char* value()
  {
    return DataType< ::panda_move::ActionSequences >::value();
  }
  static const char* value(const ::panda_move::ActionSequencesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_ACTIONSEQUENCES_H
