// Generated by gencpp from file panda_move/Hand.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_HAND_H
#define PANDA_MOVE_MESSAGE_HAND_H

#include <ros/service_traits.h>


#include <panda_move/HandRequest.h>
#include <panda_move/HandResponse.h>


namespace panda_move
{

struct Hand
{

typedef HandRequest Request;
typedef HandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Hand
} // namespace panda_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_move::Hand > {
  static const char* value()
  {
    return "90c7acc194a7a7121ca85308c4242240";
  }

  static const char* value(const ::panda_move::Hand&) { return value(); }
};

template<>
struct DataType< ::panda_move::Hand > {
  static const char* value()
  {
    return "panda_move/Hand";
  }

  static const char* value(const ::panda_move::Hand&) { return value(); }
};


// service_traits::MD5Sum< ::panda_move::HandRequest> should match
// service_traits::MD5Sum< ::panda_move::Hand >
template<>
struct MD5Sum< ::panda_move::HandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::Hand >::value();
  }
  static const char* value(const ::panda_move::HandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::HandRequest> should match
// service_traits::DataType< ::panda_move::Hand >
template<>
struct DataType< ::panda_move::HandRequest>
{
  static const char* value()
  {
    return DataType< ::panda_move::Hand >::value();
  }
  static const char* value(const ::panda_move::HandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_move::HandResponse> should match
// service_traits::MD5Sum< ::panda_move::Hand >
template<>
struct MD5Sum< ::panda_move::HandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::Hand >::value();
  }
  static const char* value(const ::panda_move::HandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::HandResponse> should match
// service_traits::DataType< ::panda_move::Hand >
template<>
struct DataType< ::panda_move::HandResponse>
{
  static const char* value()
  {
    return DataType< ::panda_move::Hand >::value();
  }
  static const char* value(const ::panda_move::HandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_HAND_H
