// Generated by gencpp from file panda_move/InitResponse.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_INITRESPONSE_H
#define PANDA_MOVE_MESSAGE_INITRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_move
{
template <class ContainerAllocator>
struct InitResponse_
{
  typedef InitResponse_<ContainerAllocator> Type;

  InitResponse_()
    : init_state(0)  {
    }
  InitResponse_(const ContainerAllocator& _alloc)
    : init_state(0)  {
  (void)_alloc;
    }



   typedef int64_t _init_state_type;
  _init_state_type init_state;





  typedef boost::shared_ptr< ::panda_move::InitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_move::InitResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitResponse_

typedef ::panda_move::InitResponse_<std::allocator<void> > InitResponse;

typedef boost::shared_ptr< ::panda_move::InitResponse > InitResponsePtr;
typedef boost::shared_ptr< ::panda_move::InitResponse const> InitResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_move::InitResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_move::InitResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_move::InitResponse_<ContainerAllocator1> & lhs, const ::panda_move::InitResponse_<ContainerAllocator2> & rhs)
{
  return lhs.init_state == rhs.init_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_move::InitResponse_<ContainerAllocator1> & lhs, const ::panda_move::InitResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::InitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::InitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::InitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::InitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::InitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::InitResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_move::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a848b0441b20a5cbb45558b3d0978950";
  }

  static const char* value(const ::panda_move::InitResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa848b0441b20a5cbULL;
  static const uint64_t static_value2 = 0xb45558b3d0978950ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_move::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_move/InitResponse";
  }

  static const char* value(const ::panda_move::InitResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_move::InitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 init_state\n"
;
  }

  static const char* value(const ::panda_move::InitResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_move::InitResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_move::InitResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_move::InitResponse_<ContainerAllocator>& v)
  {
    s << indent << "init_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.init_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_INITRESPONSE_H
