// Generated by gencpp from file panda_move/MotionCheckResponse.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_MOTIONCHECKRESPONSE_H
#define PANDA_MOVE_MESSAGE_MOTIONCHECKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_move
{
template <class ContainerAllocator>
struct MotionCheckResponse_
{
  typedef MotionCheckResponse_<ContainerAllocator> Type;

  MotionCheckResponse_()
    : execute_state(0)  {
    }
  MotionCheckResponse_(const ContainerAllocator& _alloc)
    : execute_state(0)  {
  (void)_alloc;
    }



   typedef int64_t _execute_state_type;
  _execute_state_type execute_state;





  typedef boost::shared_ptr< ::panda_move::MotionCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_move::MotionCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotionCheckResponse_

typedef ::panda_move::MotionCheckResponse_<std::allocator<void> > MotionCheckResponse;

typedef boost::shared_ptr< ::panda_move::MotionCheckResponse > MotionCheckResponsePtr;
typedef boost::shared_ptr< ::panda_move::MotionCheckResponse const> MotionCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_move::MotionCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_move::MotionCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_move::MotionCheckResponse_<ContainerAllocator1> & lhs, const ::panda_move::MotionCheckResponse_<ContainerAllocator2> & rhs)
{
  return lhs.execute_state == rhs.execute_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_move::MotionCheckResponse_<ContainerAllocator1> & lhs, const ::panda_move::MotionCheckResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::MotionCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::MotionCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::MotionCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e5da242623a66ea9b9fa2f917d3d039";
  }

  static const char* value(const ::panda_move::MotionCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e5da242623a66eaULL;
  static const uint64_t static_value2 = 0x9b9fa2f917d3d039ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_move/MotionCheckResponse";
  }

  static const char* value(const ::panda_move::MotionCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 execute_state\n"
;
  }

  static const char* value(const ::panda_move::MotionCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_move::MotionCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_move::MotionCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "execute_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.execute_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_MOTIONCHECKRESPONSE_H
