// Generated by gencpp from file panda_move/MotionCheck.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_MOTIONCHECK_H
#define PANDA_MOVE_MESSAGE_MOTIONCHECK_H

#include <ros/service_traits.h>


#include <panda_move/MotionCheckRequest.h>
#include <panda_move/MotionCheckResponse.h>


namespace panda_move
{

struct MotionCheck
{

typedef MotionCheckRequest Request;
typedef MotionCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotionCheck
} // namespace panda_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_move::MotionCheck > {
  static const char* value()
  {
    return "f3ead81734321a8717b9ae871d1b0fcb";
  }

  static const char* value(const ::panda_move::MotionCheck&) { return value(); }
};

template<>
struct DataType< ::panda_move::MotionCheck > {
  static const char* value()
  {
    return "panda_move/MotionCheck";
  }

  static const char* value(const ::panda_move::MotionCheck&) { return value(); }
};


// service_traits::MD5Sum< ::panda_move::MotionCheckRequest> should match
// service_traits::MD5Sum< ::panda_move::MotionCheck >
template<>
struct MD5Sum< ::panda_move::MotionCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::MotionCheck >::value();
  }
  static const char* value(const ::panda_move::MotionCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::MotionCheckRequest> should match
// service_traits::DataType< ::panda_move::MotionCheck >
template<>
struct DataType< ::panda_move::MotionCheckRequest>
{
  static const char* value()
  {
    return DataType< ::panda_move::MotionCheck >::value();
  }
  static const char* value(const ::panda_move::MotionCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_move::MotionCheckResponse> should match
// service_traits::MD5Sum< ::panda_move::MotionCheck >
template<>
struct MD5Sum< ::panda_move::MotionCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::MotionCheck >::value();
  }
  static const char* value(const ::panda_move::MotionCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::MotionCheckResponse> should match
// service_traits::DataType< ::panda_move::MotionCheck >
template<>
struct DataType< ::panda_move::MotionCheckResponse>
{
  static const char* value()
  {
    return DataType< ::panda_move::MotionCheck >::value();
  }
  static const char* value(const ::panda_move::MotionCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_MOTIONCHECK_H
