// Generated by gencpp from file panda_move/NewStateRequest.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_NEWSTATEREQUEST_H
#define PANDA_MOVE_MESSAGE_NEWSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <panda_move/Predicate.h>

namespace panda_move
{
template <class ContainerAllocator>
struct NewStateRequest_
{
  typedef NewStateRequest_<ContainerAllocator> Type;

  NewStateRequest_()
    : new_state()  {
    }
  NewStateRequest_(const ContainerAllocator& _alloc)
    : new_state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::panda_move::Predicate_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::panda_move::Predicate_<ContainerAllocator> >::other >  _new_state_type;
  _new_state_type new_state;





  typedef boost::shared_ptr< ::panda_move::NewStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_move::NewStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NewStateRequest_

typedef ::panda_move::NewStateRequest_<std::allocator<void> > NewStateRequest;

typedef boost::shared_ptr< ::panda_move::NewStateRequest > NewStateRequestPtr;
typedef boost::shared_ptr< ::panda_move::NewStateRequest const> NewStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_move::NewStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_move::NewStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_move::NewStateRequest_<ContainerAllocator1> & lhs, const ::panda_move::NewStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.new_state == rhs.new_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_move::NewStateRequest_<ContainerAllocator1> & lhs, const ::panda_move::NewStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::NewStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::NewStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::NewStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::NewStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::NewStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::NewStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_move::NewStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9923c8d2a4b7b22cd97fde815a9ab05";
  }

  static const char* value(const ::panda_move::NewStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9923c8d2a4b7b22ULL;
  static const uint64_t static_value2 = 0xcd97fde815a9ab05ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_move::NewStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_move/NewStateRequest";
  }

  static const char* value(const ::panda_move::NewStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_move::NewStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_move/Predicate[] new_state\n"
"\n"
"================================================================================\n"
"MSG: panda_move/Predicate\n"
"string name\n"
"string[] params\n"
;
  }

  static const char* value(const ::panda_move::NewStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_move::NewStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.new_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NewStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_move::NewStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_move::NewStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "new_state[]" << std::endl;
    for (size_t i = 0; i < v.new_state.size(); ++i)
    {
      s << indent << "  new_state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::panda_move::Predicate_<ContainerAllocator> >::stream(s, indent + "    ", v.new_state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_NEWSTATEREQUEST_H
