// Generated by gencpp from file panda_move/NewState.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_NEWSTATE_H
#define PANDA_MOVE_MESSAGE_NEWSTATE_H

#include <ros/service_traits.h>


#include <panda_move/NewStateRequest.h>
#include <panda_move/NewStateResponse.h>


namespace panda_move
{

struct NewState
{

typedef NewStateRequest Request;
typedef NewStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NewState
} // namespace panda_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_move::NewState > {
  static const char* value()
  {
    return "92d4a807a3e01f714a92618d52a8f78f";
  }

  static const char* value(const ::panda_move::NewState&) { return value(); }
};

template<>
struct DataType< ::panda_move::NewState > {
  static const char* value()
  {
    return "panda_move/NewState";
  }

  static const char* value(const ::panda_move::NewState&) { return value(); }
};


// service_traits::MD5Sum< ::panda_move::NewStateRequest> should match
// service_traits::MD5Sum< ::panda_move::NewState >
template<>
struct MD5Sum< ::panda_move::NewStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::NewState >::value();
  }
  static const char* value(const ::panda_move::NewStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::NewStateRequest> should match
// service_traits::DataType< ::panda_move::NewState >
template<>
struct DataType< ::panda_move::NewStateRequest>
{
  static const char* value()
  {
    return DataType< ::panda_move::NewState >::value();
  }
  static const char* value(const ::panda_move::NewStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_move::NewStateResponse> should match
// service_traits::MD5Sum< ::panda_move::NewState >
template<>
struct MD5Sum< ::panda_move::NewStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::NewState >::value();
  }
  static const char* value(const ::panda_move::NewStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::NewStateResponse> should match
// service_traits::DataType< ::panda_move::NewState >
template<>
struct DataType< ::panda_move::NewStateResponse>
{
  static const char* value()
  {
    return DataType< ::panda_move::NewState >::value();
  }
  static const char* value(const ::panda_move::NewStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_NEWSTATE_H
