// Generated by gencpp from file panda_move/Predicate.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_PREDICATE_H
#define PANDA_MOVE_MESSAGE_PREDICATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_move
{
template <class ContainerAllocator>
struct Predicate_
{
  typedef Predicate_<ContainerAllocator> Type;

  Predicate_()
    : name()
    , params()  {
    }
  Predicate_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::panda_move::Predicate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_move::Predicate_<ContainerAllocator> const> ConstPtr;

}; // struct Predicate_

typedef ::panda_move::Predicate_<std::allocator<void> > Predicate;

typedef boost::shared_ptr< ::panda_move::Predicate > PredicatePtr;
typedef boost::shared_ptr< ::panda_move::Predicate const> PredicateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_move::Predicate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_move::Predicate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_move::Predicate_<ContainerAllocator1> & lhs, const ::panda_move::Predicate_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_move::Predicate_<ContainerAllocator1> & lhs, const ::panda_move::Predicate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::Predicate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_move::Predicate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::Predicate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_move::Predicate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::Predicate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_move::Predicate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_move::Predicate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "166bf98220d35af21b0a4502a84afab1";
  }

  static const char* value(const ::panda_move::Predicate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x166bf98220d35af2ULL;
  static const uint64_t static_value2 = 0x1b0a4502a84afab1ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_move::Predicate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_move/Predicate";
  }

  static const char* value(const ::panda_move::Predicate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_move::Predicate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string[] params\n"
;
  }

  static const char* value(const ::panda_move::Predicate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_move::Predicate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Predicate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_move::Predicate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_move::Predicate_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_PREDICATE_H
