// Generated by gencpp from file panda_move/Sync.msg
// DO NOT EDIT!


#ifndef PANDA_MOVE_MESSAGE_SYNC_H
#define PANDA_MOVE_MESSAGE_SYNC_H

#include <ros/service_traits.h>


#include <panda_move/SyncRequest.h>
#include <panda_move/SyncResponse.h>


namespace panda_move
{

struct Sync
{

typedef SyncRequest Request;
typedef SyncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sync
} // namespace panda_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_move::Sync > {
  static const char* value()
  {
    return "d850a51077e21c58d4f7667e1676cebc";
  }

  static const char* value(const ::panda_move::Sync&) { return value(); }
};

template<>
struct DataType< ::panda_move::Sync > {
  static const char* value()
  {
    return "panda_move/Sync";
  }

  static const char* value(const ::panda_move::Sync&) { return value(); }
};


// service_traits::MD5Sum< ::panda_move::SyncRequest> should match
// service_traits::MD5Sum< ::panda_move::Sync >
template<>
struct MD5Sum< ::panda_move::SyncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::Sync >::value();
  }
  static const char* value(const ::panda_move::SyncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::SyncRequest> should match
// service_traits::DataType< ::panda_move::Sync >
template<>
struct DataType< ::panda_move::SyncRequest>
{
  static const char* value()
  {
    return DataType< ::panda_move::Sync >::value();
  }
  static const char* value(const ::panda_move::SyncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_move::SyncResponse> should match
// service_traits::MD5Sum< ::panda_move::Sync >
template<>
struct MD5Sum< ::panda_move::SyncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_move::Sync >::value();
  }
  static const char* value(const ::panda_move::SyncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_move::SyncResponse> should match
// service_traits::DataType< ::panda_move::Sync >
template<>
struct DataType< ::panda_move::SyncResponse>
{
  static const char* value()
  {
    return DataType< ::panda_move::Sync >::value();
  }
  static const char* value(const ::panda_move::SyncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVE_MESSAGE_SYNC_H
