//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaMove
{
    public class MHandResponse : Message
    {
        public const string RosMessageName = "panda_move/Hand";

        public long execute_state;

        public MHandResponse()
        {
            this.execute_state = 0;
        }

        public MHandResponse(long execute_state)
        {
            this.execute_state = execute_state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.execute_state));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.execute_state = BitConverter.ToInt64(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MHandResponse: " +
            "\nexecute_state: " + execute_state.ToString();
        }
    }
}
