//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaMove
{
    public class MInitResponse : Message
    {
        public const string RosMessageName = "panda_move/Init";

        public long init_state;

        public MInitResponse()
        {
            this.init_state = 0;
        }

        public MInitResponse(long init_state)
        {
            this.init_state = init_state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.init_state));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.init_state = BitConverter.ToInt64(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MInitResponse: " +
            "\ninit_state: " + init_state.ToString();
        }
    }
}
