//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaMove
{
    public class MMotionCheckRequest : Message
    {
        public const string RosMessageName = "panda_move/MotionCheck";

        public string motion_type;
        public string[] object_1;
        public string[] object_2;

        public MMotionCheckRequest()
        {
            this.motion_type = "";
            this.object_1 = new string[0];
            this.object_2 = new string[0];
        }

        public MMotionCheckRequest(string motion_type, string[] object_1, string[] object_2)
        {
            this.motion_type = motion_type;
            this.object_1 = object_1;
            this.object_2 = object_2;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.motion_type));
            
            listOfSerializations.Add(BitConverter.GetBytes(object_1.Length));
            foreach(var entry in object_1)
                listOfSerializations.Add(SerializeString(entry));
            
            listOfSerializations.Add(BitConverter.GetBytes(object_2.Length));
            foreach(var entry in object_2)
                listOfSerializations.Add(SerializeString(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var motion_typeStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.motion_type = DeserializeString(data, offset, motion_typeStringBytesLength);
            offset += motion_typeStringBytesLength;
            
            var object_1ArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.object_1= new string[object_1ArrayLength];
            for(var i = 0; i < object_1ArrayLength; i++)
            {
                var object_1StringBytesLength = DeserializeLength(data, offset);
                offset += 4;
                this.object_1[i] = DeserializeString(data, offset, object_1StringBytesLength);
                offset += object_1StringBytesLength;
            }
            
            var object_2ArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.object_2= new string[object_2ArrayLength];
            for(var i = 0; i < object_2ArrayLength; i++)
            {
                var object_2StringBytesLength = DeserializeLength(data, offset);
                offset += 4;
                this.object_2[i] = DeserializeString(data, offset, object_2StringBytesLength);
                offset += object_2StringBytesLength;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MMotionCheckRequest: " +
            "\nmotion_type: " + motion_type.ToString() +
            "\nobject_1: " + System.String.Join(", ", object_1.ToList()) +
            "\nobject_2: " + System.String.Join(", ", object_2.ToList());
        }
    }
}
