//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    public class MContactInformation : Message
    {
        public const string RosMessageName = "moveit_msgs/ContactInformation";

        //  Standard ROS header contains information 
        //  about the frame in which this 
        //  contact is specified
        public MHeader header;
        //  Position of the contact point
        public Geometry.MPoint position;
        //  Normal corresponding to the contact point
        public Geometry.MVector3 normal;
        //  Depth of contact point
        public double depth;
        //  Name of the first body that is in contact
        //  This could be a link or a namespace that represents a body
        public string contact_body_1;
        public uint body_type_1;
        //  Name of the second body that is in contact
        //  This could be a link or a namespace that represents a body
        public string contact_body_2;
        public uint body_type_2;
        public const uint ROBOT_LINK = 0;
        public const uint WORLD_OBJECT = 1;
        public const uint ROBOT_ATTACHED = 2;

        public MContactInformation()
        {
            this.header = new MHeader();
            this.position = new Geometry.MPoint();
            this.normal = new Geometry.MVector3();
            this.depth = 0.0;
            this.contact_body_1 = "";
            this.body_type_1 = 0;
            this.contact_body_2 = "";
            this.body_type_2 = 0;
        }

        public MContactInformation(MHeader header, Geometry.MPoint position, Geometry.MVector3 normal, double depth, string contact_body_1, uint body_type_1, string contact_body_2, uint body_type_2)
        {
            this.header = header;
            this.position = position;
            this.normal = normal;
            this.depth = depth;
            this.contact_body_1 = contact_body_1;
            this.body_type_1 = body_type_1;
            this.contact_body_2 = contact_body_2;
            this.body_type_2 = body_type_2;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(position.SerializationStatements());
            listOfSerializations.AddRange(normal.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.depth));
            listOfSerializations.Add(SerializeString(this.contact_body_1));
            listOfSerializations.Add(BitConverter.GetBytes(this.body_type_1));
            listOfSerializations.Add(SerializeString(this.contact_body_2));
            listOfSerializations.Add(BitConverter.GetBytes(this.body_type_2));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.position.Deserialize(data, offset);
            offset = this.normal.Deserialize(data, offset);
            this.depth = BitConverter.ToDouble(data, offset);
            offset += 8;
            var contact_body_1StringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.contact_body_1 = DeserializeString(data, offset, contact_body_1StringBytesLength);
            offset += contact_body_1StringBytesLength;
            this.body_type_1 = BitConverter.ToUInt32(data, offset);
            offset += 4;
            var contact_body_2StringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.contact_body_2 = DeserializeString(data, offset, contact_body_2StringBytesLength);
            offset += contact_body_2StringBytesLength;
            this.body_type_2 = BitConverter.ToUInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MContactInformation: " +
            "\nheader: " + header.ToString() +
            "\nposition: " + position.ToString() +
            "\nnormal: " + normal.ToString() +
            "\ndepth: " + depth.ToString() +
            "\ncontact_body_1: " + contact_body_1.ToString() +
            "\nbody_type_1: " + body_type_1.ToString() +
            "\ncontact_body_2: " + contact_body_2.ToString() +
            "\nbody_type_2: " + body_type_2.ToString();
        }
    }
}
