//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MConstraints : Message
    {
        public const string RosMessageName = "moveit_msgs/Constraints";

        //  This message contains a list of motion planning constraints.
        //  All constraints must be satisfied for a goal to be considered valid
        public string name;
        public MJointConstraint[] joint_constraints;
        public MPositionConstraint[] position_constraints;
        public MOrientationConstraint[] orientation_constraints;
        public MVisibilityConstraint[] visibility_constraints;

        public MConstraints()
        {
            this.name = "";
            this.joint_constraints = new MJointConstraint[0];
            this.position_constraints = new MPositionConstraint[0];
            this.orientation_constraints = new MOrientationConstraint[0];
            this.visibility_constraints = new MVisibilityConstraint[0];
        }

        public MConstraints(string name, MJointConstraint[] joint_constraints, MPositionConstraint[] position_constraints, MOrientationConstraint[] orientation_constraints, MVisibilityConstraint[] visibility_constraints)
        {
            this.name = name;
            this.joint_constraints = joint_constraints;
            this.position_constraints = position_constraints;
            this.orientation_constraints = orientation_constraints;
            this.visibility_constraints = visibility_constraints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            
            listOfSerializations.Add(BitConverter.GetBytes(joint_constraints.Length));
            foreach(var entry in joint_constraints)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(position_constraints.Length));
            foreach(var entry in position_constraints)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(orientation_constraints.Length));
            foreach(var entry in orientation_constraints)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(visibility_constraints.Length));
            foreach(var entry in visibility_constraints)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            
            var joint_constraintsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.joint_constraints= new MJointConstraint[joint_constraintsArrayLength];
            for(var i = 0; i < joint_constraintsArrayLength; i++)
            {
                this.joint_constraints[i] = new MJointConstraint();
                offset = this.joint_constraints[i].Deserialize(data, offset);
            }
            
            var position_constraintsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.position_constraints= new MPositionConstraint[position_constraintsArrayLength];
            for(var i = 0; i < position_constraintsArrayLength; i++)
            {
                this.position_constraints[i] = new MPositionConstraint();
                offset = this.position_constraints[i].Deserialize(data, offset);
            }
            
            var orientation_constraintsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.orientation_constraints= new MOrientationConstraint[orientation_constraintsArrayLength];
            for(var i = 0; i < orientation_constraintsArrayLength; i++)
            {
                this.orientation_constraints[i] = new MOrientationConstraint();
                offset = this.orientation_constraints[i].Deserialize(data, offset);
            }
            
            var visibility_constraintsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.visibility_constraints= new MVisibilityConstraint[visibility_constraintsArrayLength];
            for(var i = 0; i < visibility_constraintsArrayLength; i++)
            {
                this.visibility_constraints[i] = new MVisibilityConstraint();
                offset = this.visibility_constraints[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MConstraints: " +
            "\nname: " + name.ToString() +
            "\njoint_constraints: " + System.String.Join(", ", joint_constraints.ToList()) +
            "\nposition_constraints: " + System.String.Join(", ", position_constraints.ToList()) +
            "\norientation_constraints: " + System.String.Join(", ", orientation_constraints.ToList()) +
            "\nvisibility_constraints: " + System.String.Join(", ", visibility_constraints.ToList());
        }
    }
}
