//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MCostSource : Message
    {
        public const string RosMessageName = "moveit_msgs/CostSource";

        //  The density of the cost source
        public double cost_density;
        //  The volume of the cost source is represented as an
        //  axis-aligned bounding box (AABB)
        //  The AABB is specified by two of its opposite corners
        public Geometry.MVector3 aabb_min;
        public Geometry.MVector3 aabb_max;

        public MCostSource()
        {
            this.cost_density = 0.0;
            this.aabb_min = new Geometry.MVector3();
            this.aabb_max = new Geometry.MVector3();
        }

        public MCostSource(double cost_density, Geometry.MVector3 aabb_min, Geometry.MVector3 aabb_max)
        {
            this.cost_density = cost_density;
            this.aabb_min = aabb_min;
            this.aabb_max = aabb_max;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.cost_density));
            listOfSerializations.AddRange(aabb_min.SerializationStatements());
            listOfSerializations.AddRange(aabb_max.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.cost_density = BitConverter.ToDouble(data, offset);
            offset += 8;
            offset = this.aabb_min.Deserialize(data, offset);
            offset = this.aabb_max.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MCostSource: " +
            "\ncost_density: " + cost_density.ToString() +
            "\naabb_min: " + aabb_min.ToString() +
            "\naabb_max: " + aabb_max.ToString();
        }
    }
}
