//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MMotionSequenceRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/MotionSequenceRequest";

        //  List of motion planning request with a blend_radius for each.
        //  In the response of the planner all of these will be executable as one sequence.
        public MMotionSequenceItem[] items;

        public MMotionSequenceRequest()
        {
            this.items = new MMotionSequenceItem[0];
        }

        public MMotionSequenceRequest(MMotionSequenceItem[] items)
        {
            this.items = items;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(items.Length));
            foreach(var entry in items)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var itemsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.items= new MMotionSequenceItem[itemsArrayLength];
            for(var i = 0; i < itemsArrayLength; i++)
            {
                this.items[i] = new MMotionSequenceItem();
                offset = this.items[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MMotionSequenceRequest: " +
            "\nitems: " + System.String.Join(", ", items.ToList());
        }
    }
}
