//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MMotionPlanResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/MotionPlanResponse";

        //  The representation of a solution to a planning problem
        //  The corresponding robot state
        public MRobotState trajectory_start;
        //  The group used for planning (usually the same as in the request)
        public string group_name;
        //  A solution trajectory, if found
        public MRobotTrajectory trajectory;
        //  Planning time (seconds)
        public double planning_time;
        //  Error code - encodes the overall reason for failure
        public MMoveItErrorCodes error_code;

        public MMotionPlanResponse()
        {
            this.trajectory_start = new MRobotState();
            this.group_name = "";
            this.trajectory = new MRobotTrajectory();
            this.planning_time = 0.0;
            this.error_code = new MMoveItErrorCodes();
        }

        public MMotionPlanResponse(MRobotState trajectory_start, string group_name, MRobotTrajectory trajectory, double planning_time, MMoveItErrorCodes error_code)
        {
            this.trajectory_start = trajectory_start;
            this.group_name = group_name;
            this.trajectory = trajectory;
            this.planning_time = planning_time;
            this.error_code = error_code;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(trajectory_start.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.group_name));
            listOfSerializations.AddRange(trajectory.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.planning_time));
            listOfSerializations.AddRange(error_code.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.trajectory_start.Deserialize(data, offset);
            var group_nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.group_name = DeserializeString(data, offset, group_nameStringBytesLength);
            offset += group_nameStringBytesLength;
            offset = this.trajectory.Deserialize(data, offset);
            this.planning_time = BitConverter.ToDouble(data, offset);
            offset += 8;
            offset = this.error_code.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MMotionPlanResponse: " +
            "\ntrajectory_start: " + trajectory_start.ToString() +
            "\ngroup_name: " + group_name.ToString() +
            "\ntrajectory: " + trajectory.ToString() +
            "\nplanning_time: " + planning_time.ToString() +
            "\nerror_code: " + error_code.ToString();
        }
    }
}
