//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MObjectColor : Message
    {
        public const string RosMessageName = "moveit_msgs/ObjectColor";

        //  The object id for which we specify color
        public string id;
        //  The value of the color
        public Std.MColorRGBA color;

        public MObjectColor()
        {
            this.id = "";
            this.color = new Std.MColorRGBA();
        }

        public MObjectColor(string id, Std.MColorRGBA color)
        {
            this.id = id;
            this.color = color;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.id));
            listOfSerializations.AddRange(color.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var idStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.id = DeserializeString(data, offset, idStringBytesLength);
            offset += idStringBytesLength;
            offset = this.color.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MObjectColor: " +
            "\nid: " + id.ToString() +
            "\ncolor: " + color.ToString();
        }
    }
}
