//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MPlanningSceneWorld : Message
    {
        public const string RosMessageName = "moveit_msgs/PlanningSceneWorld";

        //  collision objects
        public MCollisionObject[] collision_objects;
        //  The octomap that represents additional collision data
        public Octomap.MOctomapWithPose octomap;

        public MPlanningSceneWorld()
        {
            this.collision_objects = new MCollisionObject[0];
            this.octomap = new Octomap.MOctomapWithPose();
        }

        public MPlanningSceneWorld(MCollisionObject[] collision_objects, Octomap.MOctomapWithPose octomap)
        {
            this.collision_objects = collision_objects;
            this.octomap = octomap;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(collision_objects.Length));
            foreach(var entry in collision_objects)
                listOfSerializations.Add(entry.Serialize());
            listOfSerializations.AddRange(octomap.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var collision_objectsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.collision_objects= new MCollisionObject[collision_objectsArrayLength];
            for(var i = 0; i < collision_objectsArrayLength; i++)
            {
                this.collision_objects[i] = new MCollisionObject();
                offset = this.collision_objects[i].Deserialize(data, offset);
            }
            offset = this.octomap.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MPlanningSceneWorld: " +
            "\ncollision_objects: " + System.String.Join(", ", collision_objects.ToList()) +
            "\noctomap: " + octomap.ToString();
        }
    }
}
