//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    public class MPositionConstraint : Message
    {
        public const string RosMessageName = "moveit_msgs/PositionConstraint";

        //  This message contains the definition of a position constraint.
        public MHeader header;
        //  The robot link this constraint refers to
        public string link_name;
        //  The offset (in the link frame) for the target point on the link we are planning for
        public Geometry.MVector3 target_point_offset;
        //  The volume this constraint refers to 
        public MBoundingVolume constraint_region;
        //  A weighting factor for this constraint (denotes relative importance to other constraints. Closer to zero means less important)
        public double weight;

        public MPositionConstraint()
        {
            this.header = new MHeader();
            this.link_name = "";
            this.target_point_offset = new Geometry.MVector3();
            this.constraint_region = new MBoundingVolume();
            this.weight = 0.0;
        }

        public MPositionConstraint(MHeader header, string link_name, Geometry.MVector3 target_point_offset, MBoundingVolume constraint_region, double weight)
        {
            this.header = header;
            this.link_name = link_name;
            this.target_point_offset = target_point_offset;
            this.constraint_region = constraint_region;
            this.weight = weight;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.link_name));
            listOfSerializations.AddRange(target_point_offset.SerializationStatements());
            listOfSerializations.AddRange(constraint_region.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.weight));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            var link_nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.link_name = DeserializeString(data, offset, link_nameStringBytesLength);
            offset += link_nameStringBytesLength;
            offset = this.target_point_offset.Deserialize(data, offset);
            offset = this.constraint_region.Deserialize(data, offset);
            this.weight = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MPositionConstraint: " +
            "\nheader: " + header.ToString() +
            "\nlink_name: " + link_name.ToString() +
            "\ntarget_point_offset: " + target_point_offset.ToString() +
            "\nconstraint_region: " + constraint_region.ToString() +
            "\nweight: " + weight.ToString();
        }
    }
}
