//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MRobotTrajectory : Message
    {
        public const string RosMessageName = "moveit_msgs/RobotTrajectory";

        public Trajectory.MJointTrajectory joint_trajectory;
        public Trajectory.MMultiDOFJointTrajectory multi_dof_joint_trajectory;

        public MRobotTrajectory()
        {
            this.joint_trajectory = new Trajectory.MJointTrajectory();
            this.multi_dof_joint_trajectory = new Trajectory.MMultiDOFJointTrajectory();
        }

        public MRobotTrajectory(Trajectory.MJointTrajectory joint_trajectory, Trajectory.MMultiDOFJointTrajectory multi_dof_joint_trajectory)
        {
            this.joint_trajectory = joint_trajectory;
            this.multi_dof_joint_trajectory = multi_dof_joint_trajectory;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joint_trajectory.SerializationStatements());
            listOfSerializations.AddRange(multi_dof_joint_trajectory.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joint_trajectory.Deserialize(data, offset);
            offset = this.multi_dof_joint_trajectory.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MRobotTrajectory: " +
            "\njoint_trajectory: " + joint_trajectory.ToString() +
            "\nmulti_dof_joint_trajectory: " + multi_dof_joint_trajectory.ToString();
        }
    }
}
