//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MTrajectoryConstraints : Message
    {
        public const string RosMessageName = "moveit_msgs/TrajectoryConstraints";

        //  The array of constraints to consider along the trajectory
        public MConstraints[] constraints;

        public MTrajectoryConstraints()
        {
            this.constraints = new MConstraints[0];
        }

        public MTrajectoryConstraints(MConstraints[] constraints)
        {
            this.constraints = constraints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(constraints.Length));
            foreach(var entry in constraints)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var constraintsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.constraints= new MConstraints[constraintsArrayLength];
            for(var i = 0; i < constraintsArrayLength; i++)
            {
                this.constraints[i] = new MConstraints();
                offset = this.constraints[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MTrajectoryConstraints: " +
            "\nconstraints: " + System.String.Join(", ", constraints.ToList());
        }
    }
}
