//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    public class MWorkspaceParameters : Message
    {
        public const string RosMessageName = "moveit_msgs/WorkspaceParameters";

        //  This message contains a set of parameters useful in
        //  setting up the volume (a box) in which the robot is allowed to move.
        //  This is useful only when planning for mobile parts of 
        //  the robot as well.
        //  Define the frame of reference for the box corners
        public MHeader header;
        //  The minumum corner of the box, with respect to the robot starting pose
        public Geometry.MVector3 min_corner;
        //  The maximum corner of the box, with respect to the robot starting pose
        public Geometry.MVector3 max_corner;

        public MWorkspaceParameters()
        {
            this.header = new MHeader();
            this.min_corner = new Geometry.MVector3();
            this.max_corner = new Geometry.MVector3();
        }

        public MWorkspaceParameters(MHeader header, Geometry.MVector3 min_corner, Geometry.MVector3 max_corner)
        {
            this.header = header;
            this.min_corner = min_corner;
            this.max_corner = max_corner;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(min_corner.SerializationStatements());
            listOfSerializations.AddRange(max_corner.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.min_corner.Deserialize(data, offset);
            offset = this.max_corner.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MWorkspaceParameters: " +
            "\nheader: " + header.ToString() +
            "\nmin_corner: " + min_corner.ToString() +
            "\nmax_corner: " + max_corner.ToString();
        }
    }
}
